apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
      - name: tempconverter
        image: docker.io/lcabraja/tempconverter:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: user
        - name: DB_PASS
          value: password
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: tempconverterdb
        - name: STUDENT
          value: Luka Čabraja
        - name: COLLEGE
          value: Algebra University College
